Repository humanmade/altis-privacy, pull requests merged in 2021-08, with the labels that each got.

#22 Update GTM docs to use consent triggers as exceptions
  docs/assets/gtm-tag.png
  docs/assets/gtm-trigger.png
  docs/consent/google-tag-manager.md
Labels: backport v6-branch, backport v7-branch, backport v8-branch

#26 Fix typo in the variable name
  docs/privacy-api/README.md
Labels: backport master

#28 Rename JavaScript-Reference.md to javascript-reference.md
  docs/consent/javascript-reference.md
Labels: bug, backport v5-branch, backport v6-branch, backport v7-branch, backport v8-branch
